
project_id = "exatcpxfenndpkozdnje"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[[fetch_config]]
path = "functions/create-link-token/index.ts"

[[fetch_config]]
path = "functions/exchange-public-token/index.ts"

[[fetch_config]]
path = "functions/get-accounts/index.ts"

[[fetch_config]]
path = "functions/get-transactions/index.ts"

[[fetch_config]]
path = "functions/create-gocardless-link/index.ts"

[[fetch_config]]
path = "functions/get-gocardless-accounts/index.ts"

[[fetch_config]]
path = "functions/get-gocardless-transactions/index.ts"

[[fetch_config]]
path = "functions/plaid-webhook/index.ts" 

[[fetch_config]]
path = "functions/get-gocardless-banks/index.ts"
