
project_id = "exatcpxfenndpkozdnje"

[functions.create-link-token]
verify_jwt = false

[functions.exchange-public-token]
verify_jwt = false

[functions.sync-transactions]
verify_jwt = false

[functions.plaid-webhook]
verify_jwt = false

[functions.get-accounts]
verify_jwt = false

[functions.get-transactions]
verify_jwt = false

[functions.webhook-logs]
verify_jwt = false

[functions.create-gocardless-link]
verify_jwt = false

[functions.get-gocardless-accounts]
verify_jwt = false

[functions.get-gocardless-transactions]
verify_jwt = false
