
project_id = "exatcpxfenndpkozdnje"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[functions.create-link-token]
verify_jwt = true

[functions.exchange-public-token]
verify_jwt = true

[functions.get-accounts]
verify_jwt = true

[functions.get-transactions]
verify_jwt = true

[functions.create-gocardless-link]
verify_jwt = true

[functions.get-gocardless-accounts]
verify_jwt = true

[functions.get-gocardless-transactions]
verify_jwt = true

[functions.plaid-webhook]
verify_jwt = false

[functions.get-gocardless-banks]
verify_jwt = true
